---
- hosts: local
  tasks:
    - name: Install PHP-FPM
      apt: name=php5-fpm state=installed update_cache=yes

    - name: Install PHP packages
      apt: pkg={{ item }} state=installed
      with_items:
        - php5-mysql
        - php5-curl
        - php5-gd
        - php5-intl
        - php-pear
        - php5-imagick
        - php5-imap
        - php5-mcrypt
        - php5-memcache
        - php5-pspell
        - php5-recode
        - php5-snmp
        - php5-sqlite
        - php5-tidy
        - php5-xmlrpc
        - php5-xsl

    - name: Install PHP-APC
      apt: name=php-apc state=installed

    - name: Install fcgiwrap
      apt: name=fcgiwrap state=installed

    - name: Disable potential PHP security risk
      lineinfile: dest=/etc/php5/fpm/php.ini regexp='^(.*)cgi.fix_pathinfo=' line='cgi.fix_pathinfo=0'

    - name: Remove Apache web server
      apt: pkg={{ item }} state=absent
      with_items:
        - apache2
        - apache2.2-common
        - apache2-doc
        - apache2-mpm-prefork
        - apache2-utils
      notify:
        - Start php-fpm

  handlers:
    - name: Start php-fpm
      service: name=php5-fpm state=restarted
