---
- name: Add Dotdeb GPG key
  tags: dotdeb
  apt_key:
    url: http://www.dotdeb.org/dotdeb.gpg
    state: present

- name: Add Dotdeb repositories
  tags: dotdeb
  apt_repository:
    repo: 'deb http://packages.dotdeb.org jessie all'
    state: present

- name: Update apt cache
  tags: dotdeb
  apt:
    update_cache: yes
