---
- name: start mysql server
  service:
    name: mysql-server
    state: restarted

  - name: start php-fpm
    service:
      name: php5-fpm
      state: restarted
      
  - name: start nginx
    service:
      name: nginx
      state: restarted
